### ISSUE TITLE
Vite problem

### ISSUE THREAD

**Issue by Sitarman** [jeroenpelgrims/sveltekit-firebase-auth-server-side#2]
I cannot get Vite to build, Jeroen and debug logs do not offer any help.I take it you achieved a build if so are there any further steps I need to take. Cheers Steve

**Comment by jeroenpelgrims** [comment]
It seems some things have changed in the firebase library since I wrote the blog post I have the impression.  
I'll see if I can get this example code to work again. I'll update this issue then.

**Comment by jeroenpelgrims** [comment]
It seems the interface to the `firebase-admin` library has changed, or at least the typescript types.  
I've updated the code in the `src/lib/firebase/admin.ts` file.  

I've also updated the readme to include some minimal steps to get this repo running.  
I still need to update the blog post though.

Thanks for the report.

**Comment by Sitarman** [comment]
Cheers, Jeroen I have updated as to your revision and sveltekit now builds.
I may out of scope here as server side  is not my strong point at all but
when deploying to Cloudflare the build fails with the following error
...RollupError: "PUBLIC_FIREBASE_API_KEY" is not exported by
"$env/static/public", imported by "src/lib/firebase/client.ts".  This looks
like a sveltkit problem to me!

**Comment by jeroenpelgrims** [comment]
I've mentioned this in the [blog post](https://jeroenpelgrims.com/access-the-firebase-auth-user-in-sveltekit-server-side/#client-side-config-code).

After running one of the following commands the types should be generated: `npm run dev`, `npm run build`.

**Comment by Sitarman** [comment]
The errors were my fault when trying to deploy to Cloudflare pages which
requires env variables to be added in the cloudflare dashboard.  Cloudflare
pages still doesnt work though it is beginning to dawn on me that any
deploy with firebase-admin sdk will require a personal VM , I tried with
ngrok locally and it works perfectly well really no problems at all.
